sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t smohajer85/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true smohajer85/docker-react npm run test
